# ~/.config/sheldon/plugins.toml

shell = "zsh"

[plugins.zsh-autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh-syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.zsh-completions]
github = "zsh-users/zsh-completions"

[plugins.zsh-history-substring-search]
github = "zsh-users/zsh-history-substring-search"

# enhancd (cd強化) - 使いたい場合
[plugins.enhancd]
github = "b4b4r07/enhancd"
