# ã‚¨ãƒ‡ã‚£ã‚¿ãƒ¼ã®è£œå®Œã‚’è¨­å®šã‚¹ã‚­ãƒ¼ãƒã«åˆã‚ã›ã¦å–å¾—
"$schema" = 'https://starship.rs/config-schema.json'

# ã‚·ã‚§ãƒ«ã®ãƒ—ãƒ­ãƒ³ãƒ—ãƒˆã®é–“ã«ç©ºè¡Œã‚’æŒ¿å…¥ã™ã‚‹
add_newline = true

# ref https://github.com/starship/starship/discussions/1107?sort=top#discussioncomment-10214050
format = """
[â•­ğŸŒ ](bold green)$username$directory$battery$all$line_break$character"""

[character]
success_symbol = '[â•°â”€>](bold green)'
error_symbol = '[â•°â”€>](bold green)'

[status]
disabled = false
style = "red"
symbol = " \\(â•¯Â°â–¡Â°ï¼‰â•¯ï¸µ â”»â”â”» "
format = "\b[$symbol$status](fg:$style)"

[git_branch]
format = '[$symbol$branch(:$remote_branch) ]($style)'

# ref https://github.com/starship/starship/discussions/1107#discussioncomment-345147
[git_status]
style = "#f05133"
format = "($conflicted$staged$modified$renamed$deleted$untracked$stashed$ahead_behind\b )"
conflicted = "[ ](fg:88)[   ${count} ](fg:white bg:88)[ ](fg:88)"
staged = "[M$count ](fg:green)"
modified = "[M${count} ](fg:red)"
renamed = "[R${count} ](fg:208)"
deleted = "[ ${count} ](fg:208)"
untracked = "[?${count} ](fg:red)"
up_to_date = '[âœ“](bold green)'
stashed = "[ğŸ“¦${count} ](fg:cyan)"
ahead = "[ ${count} ](fg:purple)"
behind = "[ ${count} ](fg:yellow)"
diverged = "[](fg:88)[  × Ö¼ ](fg:white bg:88)[ ${ahead_count} ](fg:purple bg:88)[ ${behind_count} ](fg:yellow bg:88)[ ](fg:88)"

[time]
disabled = false
format = 'ğŸ•™ [$time]($style) '
time_format = '%m/%d %R'

[aws]
disabled = true

[gcloud]
disabled = true
